### ISSUE TITLE
Remove @autowired annotation

### ISSUE THREAD

**Issue by najiboulhouch** [nicholasrv/PetShopAPI#1]
https://github.com/nicholasrv/PetShopAPI/blob/24560a255d44be9936137bfec160ec40f29234b9/src/main/java/com/example/PetShopAPI/controller/DogController.java#L19

You don't need to use this annotation if you do DI by Constructor.
to do more, you can just use @RequiredArgsConstructor intead.

**Comment by nicholasrv** [comment]
Thank you Najib! Didn't realize that before.

**Comment by najiboulhouch** [comment]
W're welcome, i've used always in my projects, check this class [order-service/src/main/java/net/najiboulhouch/orderservice/controller/OrderController.java](https://github.com/najiboulhouch/shopping-online-microservices/blob/master/order-service/src/main/java/net/najiboulhouch/orderservice/controller/OrderController.java)
